### ISSUE TITLE
Support download GDrive folders (Team Drive)

### ISSUE THREAD

**Issue by OryWareKyrie** [lzzy12/python-aria-mirror-bot#102]
it would be possible to add support for downloading gdrive folders, including Team Drive.
great job this one of you

**Comment by OryWareKyrie** [comment]
@yshalsager I am aware of it but I want to compress some files that are on my TD and not copy them

**Comment by hjyoung1** [comment]
> @yshalsager I am aware of it but I want to compress some files that are on my TD and not copy them

This is mirror bot, not gdrive manager bot.
