### ISSUE TITLE
Service Account Error. Is there a way to fix?

### ISSUE THREAD

**Issue by em108** [lzzy12/python-aria-mirror-bot#105]
To the end / last pages of the attached log, the bot is able to upload the files but in some unusual cases uploads the same file over and over again using service accounts till rate limit exceeded (even though there was no upload activity using the SA in the last 24 hours), switches to the next account, uploads the same previously failed file using the next SA and goes on. It's also detailed in the screenshot using staging 4.0 before the mega.nz commit
[Log File](https://del.dog/loliphalip.txt) 

Example: the same S01E09 was uploaded several times till all the 200SA were used up
![Screenshot_20200614-181126_MiXplorer](https://user-images.githubusercontent.com/35030185/84597344-0d3ca280-ae6c-11ea-9172-4522196612ae.jpg)

And returned this error
![Screenshot_20200614-182530_Telegram](https://user-images.githubusercontent.com/35030185/84597399-79b7a180-ae6c-11ea-8960-c610a2439b68.jpg)

**Comment by lzzy12** [comment]
Make sure you have this commit https://github.com/lzzy12/python-aria-mirror-bot/commit/c791b39785b222783ebeefee5338e7ee86957682 anyway, use master branch for stability

**Comment by em108** [comment]
Thanks for the advice! I'll switch to master branch and see.
