### ISSUE TITLE
Manually upload SA?

### ISSUE THREAD

**Issue by sagirisayang** [lzzy12/python-aria-mirror-bot#106]
I've had SAs (created with folderclone) already and I want to upload and use it with the bot.
Where exactly is the directory of SAs that are supposed to be?
I uploaded it to /accounts and /projects, but none of them worked, the bot just stopped at "Downloading" state

And what exactly characters do I need to fill USE_SERVICE_ACCOUNTS in config.env? "True" or "true" or something else?

**Comment by AlbionWhite07** [comment]
@sagirisayang Have you renamed your service accs accordingly? (Use this if you haven't - https://t.me/pythonmirrorsupport/40560)

**Comment by sagirisayang** [comment]
@AlbionWhite07 Thanks, it's working properly now. 
So... the built-in SA creator in this repo makes .json files with ordered numbers (It's different with the folderclone that uses random numbers and letters)
