### ISSUE TITLE
Bot does not uploading file to google drive.

### ISSUE THREAD

**Issue by DevTeady** [lzzy12/python-aria-mirror-bot#109]
I've deploy the bot in Ubuntu 18.01LTS in Azure.But when I had cloned stage 3,there is no  secret json in config.env .please help me to understand how to set secret JSON in config.env.
Noted: My bot is activated but dont upload file to drive.

Please help🙏🙏

**Comment by hjyoung1** [comment]
Staging-3.0 is outdated now. Use master or staging-4.0 (if you want to test new features)
And what do you mean by secret json?

**Comment by DevTeady** [comment]
> Staging-3.0 is outdated now. Use master or staging-4.0 (if you want to test new features)
> And what do you mean by secret json?

It's solved bro.tnx for reply
