### ISSUE TITLE
Add support for uploading to shared drives

### ISSUE THREAD

**Issue by telegrambotdev** [lzzy12/python-aria-mirror-bot#11]
is this repo supports googls shared drives  uploading?

**Comment by lzzy12** [comment]
It's not tested. I would suggest, test it and report. Closing this for now. Reopen if it doesn't work

**Comment by lzzy12** [comment]
Just got to know that it isn't allowed to get shared links of files uploaded to shared drives. So this is not possible to be implemented because of how the bot works

**Comment by lzzy12** [comment]
https://github.com/lzzy12/python-aria-mirror-bot/commit/0ed1ca3531ac942b2352f7977ab5372c118f7e70

**Comment by telegrambotdev** [comment]
but this guy added support for google shared drive ! check this

https://github.com/out386/aria-telegram-mirror-bot/commit/290385349d46ab4612efc85f99933903c5d8d16c

**Comment by lzzy12** [comment]
@telegrambotdev We have added TD support as well.

**Comment by eliasbenb** [comment]
When did you do that? And how do I enable it

> @telegrambotdev We have added TD support as well.

**Comment by lzzy12** [comment]
@eliasbenb It's in develop branch. Wait for it to get merged in master before you deploy. However if you want to test it out check the readme file in develop branch
