### ISSUE TITLE
change command /mirror

### ISSUE THREAD

**Issue by adisubagja** [lzzy12/python-aria-mirror-bot#111]
how to edit or change command /mirror sir? i'll change to /drive /tardrive

**Comment by AlbionWhite07** [comment]
@adisubagja by reading the readme.md

**Comment by adisubagja** [comment]
where file must edited?

**Comment by AlbionWhite07** [comment]
@adisubagja To change bot commands, you need to change the strings in the file located at bot/helper/telegram_helper/bot_commands.py

**Comment by adisubagja** [comment]
Thanks for help :)
Thanks you very match this solved
