### ISSUE TITLE
Can't mirror seedr.cc links

### ISSUE THREAD

**Issue by Hashimkp** [lzzy12/python-aria-mirror-bot#117]

**Comment by Akshaygit1** [comment]
Seedr link Works fine for me. Give logs.

**Comment by Hashimkp** [comment]
Its showing "your download has been stopped due to: SSL/TLS handshake failure:  `not signed by known authorities or invalid' `expired"

**Comment by IamyashXD** [comment]
@Hashimkp Add this in aria.sh

--check-certificate=false

**Comment by Hashimkp** [comment]
Done
