### ISSUE TITLE
Stuck on MetaData

### ISSUE THREAD

**Issue by Rajwadkar07** [lzzy12/python-aria-mirror-bot#12]
Hey brother. First of all thanks for your hard work. The issue I am facing is the bot gets stuck on Metadata even when torrent that has seeds (Joker BluRay for now). I tried other few torrents too... Same issue. But its working for DDLs. What can I do to fix this? Also I couldn't cancel torrents using /cancelmirror as only the /mirror command is working for me.

**Comment by eliasbenb** [comment]
First of all, the command to cancel a download is /mirror. Now for your torrents issue, did you deploy this on Docker or Heroku?

**Comment by Rajwadkar07** [comment]
Deployed it on heroku

**Comment by Rajwadkar07** [comment]
Deployed it on heroku and followed the steps same as readme. Also how can command to cancel be /mirror ?

**Comment by eliasbenb** [comment]
Sorry, the command to cancel is /cancel (in reply). Do /help for all the commands.

Also since you deployed your app on Heroku what most probably happened is that Heroku blocked p2p on your app (they don't like it when users abuse p2p on their apps). Or your app is on a break. Heroku requires that every app has a 6 hour break every day. Try again in 5 hours to see if it works

**Comment by Rajwadkar07** [comment]
Okay sure. I'll let you know. Thanks bruv ❤️

**Comment by Rajwadkar07** [comment]
Sorry but DDL downloading is stuck now at 100% 🙁

**Comment by eliasbenb** [comment]
That means you messed up somewhere when setting up the bot. I'm guessing you either messed up the token.pickle file or the credentials.jason file. Check those

**Comment by a092devs** [comment]
@Rajwadkar07 Tried restarting dynos? This sometimes help.
Also, which server is your app hosted in?

**Comment by Rajwadkar07** [comment]
Hosted on Heroku sir

**Comment by eliasbenb** [comment]
United states

**Comment by Rajwadkar07** [comment]
And tried restarting, didn't help

**Comment by a092devs** [comment]
> Hosted on Heroku sir

By server I meant location of heroku server (US or EU). Sorry for not being precise.

**Comment by a092devs** [comment]
@Rajwadkar07 join @pythonmirrorsupport TG group for discussion.

**Comment by Rajwadkar07** [comment]
Done

> @Rajwadkar07 join @pythonmirrorsupport TG group for discussion.

Done sir

**Comment by lzzy12** [comment]
Fixed in 0d30f19a4e508d87621965b99ca2b3e07ba2e80b
