### ISSUE TITLE
Generating User String Session Issue

### ISSUE THREAD

**Issue by Gwenstephanie** [lzzy12/python-aria-mirror-bot#120]
I tried generating user string session today but to no avail i got error like this...

![Screenshot_20200628_202913](https://user-images.githubusercontent.com/53878781/85956535-44d44000-b97e-11ea-8360-d2e545295d5e.jpg)

Is there something wrong on my side?

**Comment by a092devs** [comment]
+1, I was thinking that I messed up something lol.

**Comment by em108** [comment]
I recall having a similar issue till I upgraded pyrogram and everything worked fine afterwards. I think you should try running the pip install for pyrogram and see how it works out.

**Comment by Gwenstephanie** [comment]
> I recall having a similar issue till I upgraded pyrogram and everything worked fine afterwards. I think you should try running the pip install for pyrogram and see how it works out.

What version are you on?

**Comment by em108** [comment]
> What version are you on?
`Pyrogram 0.16.0`

You could also re-run the `pip3 install -r requirements.txt` just to be sure.
I recall that's what fixed mine

**Comment by Gwenstephanie** [comment]
> > What version are you on?
> 
> `Pyrogram 0.16.0`
> 
> You could also re-run the `pip3 install -r requirements.txt` just to be sure.
> I recall that's what fixed mine



Problem solved, thanks for helping :) please if you're on telegram drop your username so i can contact you for future purposes

**Comment by em108** [comment]
> Problem solved, thanks for helping :) please if you're on telegram drop your username so i can contact you for future purposes

No problem and glad it worked out.
You can find me at @fr108nk if you need anything.

**Comment by em108** [comment]
You could also contact anyone in @pythonmirrorsupport chat for assistance on anything

**Comment by Gwenstephanie** [comment]
Thanks alot @em108
