### ISSUE TITLE
RSS feed support

### ISSUE THREAD

**Issue by OryWareKyrie** [lzzy12/python-aria-mirror-bot#121]
I would like to know if you could implement an RSS feed to download torrents from public trackers.
I use the staging version 4.0 and I really loved the addition of the CPU info and RAM memory. congratulations

**Comment by Akshaygit1** [comment]
imo this will only make bot more heavier. Also this feature is great for some users but for majority of users they'll never use this.

**Comment by OryWareKyrie** [comment]
> imo this will only make bot more heavier. Also this feature is great for some users but for majority of users they'll never use this.

I understand your point. just put an option to disable or enable that option.

**Comment by lzzy12** [comment]
I don't intend to work on this feature.. closing. If anyone sends a PR, I can merge it.
