### ISSUE TITLE
unable to use mega sdk..pls check

### ISSUE THREAD

**Issue by evilvenom** [lzzy12/python-aria-mirror-bot#126]

**Comment by a092devs** [comment]
Its not implemented completely yet. Use master branch or deal with unstable mega if you don't wanna switch branch.

**Comment by ktanay98** [comment]
Was using mega since 2nd June without issues...but was trying to update it...just checked that the commits for mega were reverted...sad...keep doing good work...thanks...hope mega support returns soon

**Comment by hjyoung1** [comment]
https://github.com/lzzy12/python-aria-mirror-bot/tree/staging-4.0-mega

**Comment by ktanay98** [comment]
> https://github.com/lzzy12/python-aria-mirror-bot/tree/staging-4.0-mega

Tried that...but i get submodule error which I fixed by adding submodule to .gitmodules manually...but total 16 steps are built and mega doesn't work...when mega is built too there's 21 steps

**Comment by hjyoung1** [comment]
> > https://github.com/lzzy12/python-aria-mirror-bot/tree/staging-4.0-mega
> 
> Tried that...but i get submodule error which I fixed by adding submodule to .gitmodules manually...but total 16 steps are built and mega doesn't work...when mega is built too there's 21 steps

Well obviously that's why it in staging and separate branch too, it's unstable buggy. 
Imo devs better drop mega support it's not worth all this trouble.
