### ISSUE TITLE
Bot name append

### ISSUE THREAD

**Issue by herrysis404** [lzzy12/python-aria-mirror-bot#130]
How to set bot only work if someone type bots name
example /mirror@botname

**Comment by dhruvan2912** [comment]
@herrysis404 Long press on command?🤔

**Comment by herrysis404** [comment]
i have 2 bot in the group. When someone type /mirror the both bot process that command. It became double

**Comment by AlbionWhite07** [comment]
@herrysis404 Change commands for the 2nd bot

**Comment by herrysis404** [comment]
Which file the command code?

**Comment by AlbionWhite07** [comment]
@herrysis404 To change bot commands, you need to change the strings in the file located at bot/helper/telegram_helper/bot_commands.py

**Comment by herrysis404** [comment]
thankyou sir.
