### ISSUE TITLE
Aria Not Canceling If can't Get metadata Torrent

### ISSUE THREAD

**Issue by tomyprs25** [lzzy12/python-aria-mirror-bot#133]
@lzzy12 Bro How to auto cancel download if can't Get meta data of torrent?

**Comment by WiizarDxD** [comment]
@tomyprs25 Add this in aria.sh 

--bt-stop-timeout=(time)

**Comment by tomyprs25** [comment]
@WiizarDxD Thanks bro , try now

**Comment by tomyprs25** [comment]
Thanks solved
