### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by NandiyaLive** [lzzy12/python-aria-mirror-bot#136]
How can I authorize a group to use the bot

**Comment by noobvishal** [comment]
@NandiyaLive Use /authorize cmd in the chat

**Comment by NandiyaLive** [comment]
Nothing happened. Then will it respond to anyone on a group that I add the bot

**Comment by a092devs** [comment]
@NandiyaLive yes, do /help to know more

**Comment by NandiyaLive** [comment]
Are you trying to say that when I /authorize on bot anyone can use it?

**Comment by noobvishal** [comment]
@NandiyaLive You have to type and send /authorize in the group without replying to anyone to authorize the members so that they are able to use your bot.

**Comment by NandiyaLive** [comment]
thanx brothers

**Comment by NandiyaLive** [comment]
So how can I authorize a single user

**Comment by adisubagja** [comment]
@NandiyaLive reply to user /authorize
