### ISSUE TITLE
[Request] information about seeds and peers while downloading torrents 

### ISSUE THREAD

**Issue by krishne35** [lzzy12/python-aria-mirror-bot#14]
This information will be useful as we can cancel the download if the seeds are too low!!

**Comment by smartass08** [comment]
> This information will be useful as we can cancel the download if the seeds are too low!!

Wait don't you know about seeds before adding the torrent?

**Comment by krishne35** [comment]
Most of the torrentz won't provide present seeds and peers :p

**Comment by krishne35** [comment]
Thanks :)

**Comment by lzzy12** [comment]
@krishne35 why did you close it? We are going to add it soon. Just busy

**Comment by krishne35** [comment]
> @krishne35 why did you close it? We are going to add it soon. Just busy

It's added in develop branch :p

**Comment by lzzy12** [comment]
> > @krishne35 why did you close it? We are going to add it soon. Just busy
> 
> It's added in develop branch :p

Oh lmao. I'm off for a bit. Was Not aware of that commit
