### ISSUE TITLE
Uploading randomly fails

### ISSUE THREAD

**Issue by thegreatestminer** [lzzy12/python-aria-mirror-bot#143]
Sometimes when I mirror a torrent, it fails to upload when it finishes downloading. I don't know if there's any way to tell, but if it fails or times out while uploading, can it attempt to retry uploading? It's irritating to ssh into the server just to upload a file and restart the bot to clean things up.

The offending error:

```
2020-07-29 00:30:32,557 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Uploading File: /home/ztgasdf/mirror-bot/downloads/560/filename.zip
2020-07-29 00:30:53,140 - bot.helper.mirror_utils.upload_utils.gdriveTools - ERROR - [Errno 104] Connection reset by peer
```

**Comment by lzzy12** [comment]
I can't recreate this issue. Maybe some network problem. Bot already retries 5 times if the request fails.

**Comment by thegreatestminer** [comment]
@lzzy12 Where can I modify the script to infinitely retry until it uploads? I agree, it's probably something to do with my internet.

**Comment by thegreatestminer** [comment]
Closed because I haven't used this in a long time, and it seemed to just be an issue on my side.
