### ISSUE TITLE
yt-dl grabs HTML page named "watch".

### ISSUE THREAD

**Issue by elbert505** [lzzy12/python-aria-mirror-bot#147]
So, I've finally managed to make the bot work for me, both locally & in VPS. 
Torrents & DDLs are working fine, however yt-dl part doesn't work for me, as it should. 
Tried with Youtube & Dailymotion links & it downloads just the HTML of the link & names the file as "watch". I made sure the URL is in the right format, too.
How can i rectify this?
Thank you.

**Comment by lzzy12** [comment]
@elbert505 Send /help to get list of the commands.

**Comment by elbert505** [comment]
@lzzy12 My bad! I was fiddling with custom commands & seems the yt-dl still has the original default command. Thanks for clearing that up.
