### ISSUE TITLE
ModuleNotFoundError: No module named telegraph

### ISSUE THREAD

**Issue by fzsimlu** [lzzy12/python-aria-mirror-bot#156]
Hello, I encountered a problem, the log is as follows, how should I solve it, thank you

[root@instance-2 mirror-bot]# pip3 install telegram
Collecting telegram
  Downloading telegram-0.0.1.tar.gz (879 bytes)
Using legacy 'setup.py install' for telegram, since package 'wheel' is not installed.
Installing collected packages: telegram
    Running setup.py install for telegram ... done
Successfully installed telegram-0.0.1

[root@instance-2 mirror-bot]# python3 generate_telegraph_token.py 
Traceback (most recent call last):
  File "generate_telegraph_token.py", line 1, in <module>
    from telegraph import Telegraph
ModuleNotFoundError: No module named 'telegraph'

[root@instance-2 mirror-bot]# pip3 install telegram
Requirement already satisfied: telegram in /usr/local/lib/python3.6/site-packages (0.0.1)

**Comment by a092devs** [comment]
@fzsimlu Wrong repo dude

**Comment by jaskaranSM** [comment]
Hi, it would seem like you are using some other repository, a fork perhaps, cuz we dont have any module or connection to telegraph in this repo. So closing this.
