### ISSUE TITLE
[Enhancement] Maintain only one /stats in chat.

### ISSUE THREAD

**Issue by sawankumar** [lzzy12/python-aria-mirror-bot#167]
Just like /status, there should be one /stats message in chat to reduce clutter.

**Comment by iamlordutkarsh** [comment]
@sawankumar Already There I guess 😐

**Comment by sawankumar** [comment]
@iamlordutkarsh Only for /status.

**Comment by sawankumar** [comment]
@iamlordutkarsh ![Screenshot_20200924-114636__01.jpg](https://user-images.githubusercontent.com/33548019/94107885-f4289200-fe5b-11ea-9d6c-d4a4a689b404.jpg)

**Comment by sawankumar** [comment]
@iamlordutkarsh ![Screenshot_20200924-115146__01.jpg](https://user-images.githubusercontent.com/33548019/94108155-6c8f5300-fe5c-11ea-9614-f7d262f0540d.jpg)

**Comment by lzzy12** [comment]
This is not something I intend to work on, neither do I think there is any need to implement it. Single status message is maintained per chat because the message is actively edited by the bot and editing too many times  triggers telegram's restrictions.
