### ISSUE TITLE
The specified is not supported CAHT ID

### ISSUE THREAD

**Issue by kedyao** [lzzy12/python-aria-mirror-bot#173]
The specified is not supported CAHT ID

**Comment by Suyashjain05** [comment]
Kindly elaborate.

**Comment by kedyao** [comment]
How to authorize a group to use this robot
like this https://github.com/out386/aria-telegram-mirror-bot
SUDO_USERS: [ID,ID],	// Telegram user IDs. These users can use the bot in any chat.
AUTHORIZED_CHATS: [-CHATID,-CHATID],	// Telegram chat IDs. Anyone in these chats can use the bot.

**Comment by Suyashjain05** [comment]
owner id is for sudo user id. for authorized chats , make a file `authorized_chats.txt` in the root dir of your bot and add you chat id in that txt file.

**Comment by kedyao** [comment]
oh !Thank you for your careful answer

**Comment by Suyashjain05** [comment]
@kedyao your welcome
