### ISSUE TITLE
Error Httperror404

### ISSUE THREAD

**Issue by jamesjamesa** [lzzy12/python-aria-mirror-bot#18]
`
bot - INFO - Adding link: filelink

bot - INFO - Download completed: README.md

bot - INFO - Upload Name : README.md

bot.helper.ext_utils.bot_utils - INFO - Google Drive token already valid!

bot.helper.ext_utils.bot_utils - INFO - Uploading File: README.md

bot.helper.ext_utils.bot_utils - INFO - status: None

bot.helper.ext_utils.bot_utils - ERROR - <HttpError 404 when requesting https://www.googleapis.com/upload/drive/v3/files?alt=json&uploadType=resumable returned "File not found: 0ALrxNBX8bGUk9PVA.">
bot - ERROR - HttpError 404 when requesting https://www.googleapis.com/upload/drive/v3/files?alt=json&uploadType=resumable returned "File not found: 0ALrxBX8bGUk9PVA."
bot - INFO - Cleaning download: /bot/downloads/102
`

**Comment by jamesjamesa** [comment]
Trying to use teamdrive as source, email has manager access and is valid, using teamdrive ID as target folder

**Comment by lzzy12** [comment]
Master branch don't support Team drives as of today. You may use develop branch till develop merges into master
