### ISSUE TITLE
Direct link function not found!

### ISSUE THREAD

**Issue by flacial** [lzzy12/python-aria-mirror-bot#187]
I get this error whenever I try to use the /mirror function. And I hope using Heroku won't make troubles as I've seen people saying "we can't answer it, Heroku not supported".

https://del.dog/ygnythughe.txt

**Comment by yuno74** [comment]
Try use transload if link https use http

**Comment by Flacial** [comment]
> Try use transload if link https use http

Thanks for replying but the issue still exists. Do you have an idea on what misconfigured file could return that error?
