### ISSUE TITLE
Gdrive upload fail 

### ISSUE THREAD

**Issue by Lucky056** [lzzy12/python-aria-mirror-bot#190]
When I try to mirror a torrent, the bot downloads the file but it can't upload
-------
```
HttpError 404 when requesting https://www.googleapis.com/drive/v3/files?supportsTeamDrives=true&alt=json returned "File not found: 1UTmEtIAM9Dz_uwcp4z0mYBvQNMQwJxCd.
```
-------
I have generated token.pickle too, yet it doesn't works. And the folder exists on my Google drive so I'm not sure what the issue is.

**Comment by tylahibeb** [comment]
> ## When I try to mirror a torrent, the bot downloads the file but it can't upload
> ```
> HttpError 404 when requesting https://www.googleapis.com/drive/v3/files?supportsTeamDrives=true&alt=json returned "File not found: 1UTmEtIAM9Dz_uwcp4z0mYBvQNMQwJxCd.
> ```
> 
> I have generated token.pickle too, yet it doesn't works. And the folder exists on my Google drive so I'm not sure what the issue is.

@Lucky056 did you ever get this figured out? I'm facing the same issue.

**Comment by yuno74** [comment]
Try check credentials

**Comment by tylahibeb** [comment]
> Try check credentials

@yuno74 how so? By regenerating the token?

**Comment by yuno74** [comment]
> > Try check credentials
> 
> @yuno74 how so? By regenerating the token?

Do you make credentials file?from google cloud>gdrive api?

**Comment by tylahibeb** [comment]
> > > Try check credentials
> > 
> > 
> > @yuno74 how so? By regenerating the token?
> 
> Do you make credentials file?from google cloud>gdrive api?

I have, yes. I even generated a few new ones just in case and tried to play around with the scopes to allow for full gdrive access. Gdrive API is also enabled.

**Comment by yuno74** [comment]
> > > > Try check credentials
> > > 
> > > 
> > > @yuno74 how so? By regenerating the token?
> > 
> > 
> > Do you make credentials file?from google cloud>gdrive api?
> 
> I have, yes. I even generated a few new ones just in case and tried to play around with the scopes to allow for full gdrive access. Gdrive API is also enabled.

Google drive folder Id?and make link for public

**Comment by tylahibeb** [comment]
> > > > > Try check credentials
> > > > 
> > > > 
> > > > @yuno74 how so? By regenerating the token?
> > > 
> > > 
> > > Do you make credentials file?from google cloud>gdrive api?
> > 
> > 
> > I have, yes. I even generated a few new ones just in case and tried to play around with the scopes to allow for full gdrive access. Gdrive API is also enabled.
> 
> Google drive folder Id?and make link for public

I made sure my drive ID is correct and played around with the privacy settings. When it's full private, I get a 404. When I make it public and allow anyone to contribute, I get a 403 (Does not have sufficient permissions). I think something is wrong with my creds but I'm not sure if its the token file or the OAuth key. I've used my credentials.json in other projects like this before and it worked just fine.

**Comment by yuno74** [comment]
Make new project at GCP and create new creds

**Comment by yuno74** [comment]
> > > > > > Try check credentials
> > > > > 
> > > > > 
> > > > > @yuno74 how so? By regenerating the token?
> > > > 
> > > > 
> > > > Do you make credentials file?from google cloud>gdrive api?
> > > 
> > > 
> > > I have, yes. I even generated a few new ones just in case and tried to play around with the scopes to allow for full gdrive access. Gdrive API is also enabled.
> > 
> > 
> > Google drive folder Id?and make link for public
> 
> I made sure my drive ID is correct and played around with the privacy settings. When it's full private, I get a 404. When I make it public and allow anyone to contribute, I get a 403 (Does not have sufficient permissions). I think something is wrong with my creds but I'm not sure if its the token file or the OAuth key. I've used my credentials.json in other projects like this before and it worked just fine.

VPS or heroku?

**Comment by tylahibeb** [comment]
> Make new project at GCP and create new creds

I'll give that a shot and report back if it works.

> VPS or heroku?

Heroku
