### ISSUE TITLE
Files deleted 

### ISSUE THREAD

**Issue by Lucky056** [lzzy12/python-aria-mirror-bot#191]
I tried setting up download path as my phone storage download path for the aria bot. The folder in it were visible at first but now they aren't. Does the bot wipes the folder as initial setup automatically? I'm sorry to ask this here but I couldn't find any other way to know this. My files inside the folder are gone..... So if the bot clears files inside the folder as initial setup please mention it...

**Comment by AlbionWhite07** [comment]
@Lucky056 That's common sense, bot downloads files locally then uploads them to gdrive and deletes them from host machine after that.

**Comment by Lucky056** [comment]
Well the file wasn't even downloaded fully tho...

**Comment by Lucky056** [comment]
So like I wasn't able to access the files so I stopped the bot first and checked. It was at 94%.

**Comment by AlbionWhite07** [comment]
@Lucky056 If u want to download locally just use some bit torrent app
