### ISSUE TITLE
netrc too access too permissive

### ISSUE THREAD

**Issue by meeker0** [lzzy12/python-aria-mirror-bot#197]
as per as your dockerfile netrc is located in `/root/.netrc`  I tried to make it exicuteable but no luck!  
It shows `bot.helper.mirror_utils.download_utils.youtube_dl_download_helper - WARNING - parsing .netrc: ~/.netrc access too permissive: access permissions must restrict access to only the owner (/root/.netrc, line 1)`

**Comment by lzzy12** [comment]
Run this command and try again

``chmod og-rw .netrc`

**Comment by meeker0** [comment]
It fixed ! But please notice `chmod og-rw /root/.netrc`
