### ISSUE TITLE
Stack at downloading.. Please help

### ISSUE THREAD

**Issue by nullbytes0** [lzzy12/python-aria-mirror-bot#200]
Never Detect the dead or slow torrent.
Ihave to  manually  cancel to stop it.

Please help.

**Comment by yuno74** [comment]
Do you change or edit aria.sh?

**Comment by nullbytes0** [comment]
> Do you change or edit aria.sh?

No bruh

**Comment by yuno74** [comment]
> > Do you change or edit aria.sh?
> > Yah edit cause the default one is same problem

Maybe problem with requirement version

**Comment by nullbytes0** [comment]
> > > Do you change or edit aria.sh?
> > > Yah edit cause the default one is same problem
> 
> Maybe problem with requirement version

You have it?

**Comment by yuno74** [comment]
> > > > Do you change or edit aria.sh?
> > > > Yah edit cause the default one is same problem
> > 
> > 
> > Maybe problem with requirement version
> 
> You have it?

If you don't mind try build from my repo or compare with your

**Comment by nullbytes0** [comment]
> > > > > Do you change or edit aria.sh?
> > > > > Yah edit cause the default one is same problem
> > > 
> > > 
> > > Maybe problem with requirement version
> > 
> > 
> > You have it?
> 
> If you don't mind try build from my repo or compare with your
Can pm you sir?

**Comment by nullbytes0** [comment]
> > > > > Do you change or edit aria.sh?
> > > > > Yah edit cause the default one is same problem
> > > 
> > > 
> > > Maybe problem with requirement version
> > 
> > 
> > You have it?
> 
> If you don't mind try build from my repo or compare with your

can pm You sir on telegram?
