### ISSUE TITLE
HttpError 404 "File not found:  "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",

### ISSUE THREAD

**Issue by TanjimReza** [lzzy12/python-aria-mirror-bot#202]
Shows this on uploading. Tried setting IS_TEAM_DRIVE = "False" and USE_SERVICE_ACCOUNTS = "" 
![image](https://user-images.githubusercontent.com/35164789/104906934-88d87200-59ae-11eb-89cf-365545b3d998.png)

**Comment by nullbytes0** [comment]
Check your gdrive id

**Comment by TanjimReza** [comment]
Checked, but that wasn't the issue. Nevermind fixed. Closing.
