### ISSUE TITLE
Edit Command

### ISSUE THREAD

**Issue by thebatmanbd** [lzzy12/python-aria-mirror-bot#211]
This is not a issue rather a question. 
I would like to change the /mirror command to /download. Where do I edit this in the code? I have gone through mirror utils but could not found.

**Comment by Yash-Garg** [comment]
@thebatmanbd bot/helper/telegram_helper/bot_commands.py

**Comment by thebatmanbd** [comment]
Thank you <333

**Comment by ksssomesh12** [comment]
> This is not a issue rather a question.
> I would like to change the /mirror command to /download. Where do I edit this in the code? I have gone through mirror utils but could not found.

Find all bot commands here:

python-aria-mirror-bot/bot/helper/telegram_helper/bot_commands.py
