### ISSUE TITLE
the docker is not starting saying one or more env variable missing

### ISSUE THREAD

**Issue by mhasandx** [lzzy12/python-aria-mirror-bot#212]
here is the log of putty
using it on ubuntu 18.04 lts vps
`root@supermanonmoon:~/mirror-bot# sudo docker run mirror-bot
2021-03-02 12:51:34,048 - dotenv.main - WARNING - Python-dotenv could not parse statement starting at line 13
2021-03-02 12:51:34,104 - bot - ERROR - One or more env variables missing! Exiting now
`

**Comment by yuno74** [comment]
check config

**Comment by mhasandx** [comment]
> check config

i am clueless. i double checked config.evn for line no 13. it is user session string variaable should which filled by generating the session py. here is screenshot link https://i.imgur.com/QirjwDf.png

**Comment by yuno74** [comment]
lol you delete important enviable

**Comment by mhasandx** [comment]
> lol you delete important enviable

sorry for my being noobiness. can you help me where is the problem. i will try to fix it

**Comment by yuno74** [comment]
BOT_TOKEN = ""
GDRIVE_FOLDER_ID = ""
TELEGRAPH_TOKEN = ""
OWNER_ID =
DOWNLOAD_DIR = "/home/username/mirror-bot/downloads"
DOWNLOAD_STATUS_UPDATE_INTERVAL = 5
AUTO_DELETE_MESSAGE_DURATION = -1
IS_TEAM_DRIVE = ""
USER_SESSION_STRING = ""
TELEGRAM_API = 
TELEGRAM_HASH = ""
USE_SERVICE_ACCOUNTS = ""
# Optional config
INDEX_URL = ""
MEGA_API_KEY = ""
MEGA_EMAIL_ID = ""
MEGA_PASSWORD = ""
STOP_DUPLICATE_MIRROR = ""
BLOCK_MEGA_LINKS = ""
SHORTENER = ""
SHORTENER_API = ""
BUTTON_THREE_NAME = ""
BUTTON_THREE_URL = ""
BUTTON_FOUR_NAME = ""
BUTTON_FOUR_URL = ""
BUTTON_FIVE_NAME = ""
BUTTON_FIVE_URL = ""

**Comment by mhasandx** [comment]
@yuno74 its not working. its still saying same thing error on line 13. where as there is no line no 13 on config file...  i have also tried setting all empty variable. its also says error on line 13
screenshot link https://i.imgur.com/syXxz3Y.png

**Comment by yuno74** [comment]
you using old repo,please update it

**Comment by mhasandx** [comment]
> you using old repo,please update it
i have used the master branch repo

**Comment by yuno74** [comment]
I already check your kang repo is old version even at master branch

**Comment by yuno74** [comment]
maybe if you delete old kang and fork again will help you

**Comment by mhasandx** [comment]
> maybe if you delete old kang and fork again will help you

thank you very much. yes. i have deleted the old repo and download v5 repo. and it worked. 
love you bruh.
