### ISSUE TITLE
大佬，可以支持等待超时自动取消任务吗？

### ISSUE THREAD

**Issue by 547555909** [lzzy12/python-aria-mirror-bot#213]
有时候在群组里，很多个任务，有些死种，一直也没速度，总是要手动取消，很麻烦，如果能超过固定时间（这个时间可以自己设置最好）没速度就自动取消这个任务就好了

**Comment by yuno74** [comment]
I think that function already have

**Comment by yuno74** [comment]
@{telegram usename} your download has been stopped due to: Download stopped because dead torrent or link

for example when torrent or use dead link

**Comment by AlbionWhite07** [comment]
@547555909
