### ISSUE TITLE
The user does not have sufficient permissions

### ISSUE THREAD

**Issue by themiya66** [lzzy12/python-aria-mirror-bot#214]
![Screenshot (41)](https://user-images.githubusercontent.com/50546412/110178566-a3668d80-7e2c-11eb-8f38-f4b716618a11.png)

I deployed on heroku But this error comes when it comes to uploading the file
if this is related to token.pickle I genetrated it using my client secrets so I cant figure out what is wrong 
If anyone can Help that would be great
 edit:
 
 same happens when deployed locally or on vps

**Comment by reaitten** [comment]
> 
> 
> ![Screenshot (41)](https://user-images.githubusercontent.com/50546412/110178566-a3668d80-7e2c-11eb-8f38-f4b716618a11.png)
> 
> I deployed on heroku But this error comes when it comes to uploading the file
> if this is related to token.pickle I genetrated it using my client secrets so I cant figure out what is wrong
> If anyone can Help that would be great
> edit:
> 
> same happens when deployed locally or on vps

not sure if you got your issue resolved but just putting this out there,

I accidentally forgot to change `IS_TEAM_DRIVE` to be `true` in `config.env`
(it's supposed to be `true` because I am using a team drive.)

example:
`IS_TEAM_DRIVE = ""`
instead, it's supposed to be 
'IS_TEAM_DRIVE = "true"'

**Comment by lzzy12** [comment]
Heroku isn't supported
