### ISSUE TITLE
Stuck on 0%

### ISSUE THREAD

**Issue by AnshumanFauzdar** [lzzy12/python-aria-mirror-bot#22]
Followed all the steps, but its stuck on:
Downloading
[            ] 0.00% of 0.00 B at 0.00 B/s, ETA: -

PS- DOWNLOAD_DIR = "/home/username/mirror-bot/downloads" What directory I have to choose? I have setup a Team drive
Thanks in advance!

**Comment by krishne35** [comment]
What r u trying to download and need logs too 
don't bother about download dir

**Comment by AnshumanFauzdar** [comment]
> What r u trying to download and need logs too
> don't bother about download dir

I am trying to download from Rarbg torrent magnet to my team drive
I just removed app from heroku, will reupload and send the log
PS- Is there any need to install docker? I followed deploying from "https://github.com/lzzy12/python-aria-mirror-bot#deploying-on-heroku"

**Comment by krishne35** [comment]
Rarbg has some issues please add some 1337x torrents it should start the rarbg too 
(Request for close of issue)

**Comment by AnshumanFauzdar** [comment]
Okay, Let me try!

**Comment by AnshumanFauzdar** [comment]
> Rarbg has some issues please add some 1337x torrents it should start the rarbg too
> (Request for close of issue)
> Only need to be done once every restart
> If your deploying on heroku u dont need docker

Hey, I tried again and there is some problem with maybe magnet links, direct links are working and also .torrent file!
What is this issue and how it can be tackled?

**Comment by krishne35** [comment]
As I said it's a know issue with rarbg just add some random torrent from 1337x u should be goodto go

**Comment by AnshumanFauzdar** [comment]
> As I said it's a know issue with rarbg just add some random torrent from 1337x u should be goodto go

I added a random torrent from 1337 but nothing showed up and /status also showed nothing, but with psarips.eu torrent it works great!
