### ISSUE TITLE
sudo docker build . -t mirror-bot ===Error

### ISSUE THREAD

**Issue by dassonjoy** [lzzy12/python-aria-mirror-bot#222]
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.

**Comment by lzzy12** [comment]
This is not related to bot. Check your docker installation. [This ](https://stackoverflow.com/questions/44678725/cannot-connect-to-the-docker-daemon-at-unix-var-run-docker-sock-is-the-docker) might help.
