### ISSUE TITLE
token.pickle

### ISSUE THREAD

**Issue by brucetech627** [lzzy12/python-aria-mirror-bot#225]
Traceback (most recent call last):
  File "generate_drive_token.py", line 3, in <module>
    from google_auth_oauthlib.flow import InstalledAppFlow
ModuleNotFoundError: No module named 'google_auth_oauthlib'

**Comment by AlbionWhite07** [comment]
@brucetech627 Then install the module -_-

**Comment by yuno74** [comment]
install requirements

**Comment by yuno74** [comment]
https://github.com/lzzy12/python-aria-mirror-bot/blob/master/requirements.txt

**Comment by yuno74** [comment]
pip3 install google-api-python-client google-auth-httplib2 google-auth-oauthlib
python3 generate_drive_token.py

**Comment by lzzy12** [comment]
pip3 install -r requirements-cli.txt
