### ISSUE TITLE
Feature Request: Tag User user when download is completed

### ISSUE THREAD

**Issue by a092devs** [lzzy12/python-aria-mirror-bot#24]
https://github.com/out386/aria-telegram-mirror-bot/commit/71c74e1536cfcd7e3f81a0bb4acd49fad876124e
This helps a alot when you're in a group and some user is not able to find a DDL/magnet links and you search for a link and initiate the the download for him/her as a reply to that user.

**Comment by krishne35** [comment]
@a092devs The bot replies to the /mirror message so user will do get notified :p I don't see the need for tagging user my username

**Comment by lzzy12** [comment]
https://github.com/lzzy12/python-aria-mirror-bot/commit/457359855d0da57615f14896ff7675df8c77a87c

**Comment by a092devs** [comment]
@lzzy12 wah

**Comment by ChaitanayaMittal** [comment]
@lzzy12 Nais

**Comment by krypticallusion** [comment]
@lzzy12 Epic
