### ISSUE TITLE
authorized_chats.txt not creating by code

### ISSUE THREAD

**Issue by srijansaxena11** [lzzy12/python-aria-mirror-bot#246]
Hi. As per the code, whenever a user/chat is authorized, it should be appended to authorized_chats.txt file. But this is not happening. There is no file named authorized_chats.txt in root folder of mirror_bot. Even when created manually, this file is blank.

**Comment by lzzy12** [comment]
It happens inside the docker container.

**Comment by srijansaxena11** [comment]
> It happens inside the docker container.

where can i find it? sorry if it is a noob question.

**Comment by lzzy12** [comment]
What do you want to do? If you want to make your Authorized users persistent, you should add the ids to the authorized_users.txt file manually.

**Comment by srijansaxena11** [comment]
> What do you want to do?
Just wanted to check who all are authorized.

> If you want to make your Authorized users persistent, you should add the ids to the authorized_users.txt file manually.
This will be in root directory right?

**Comment by lzzy12** [comment]
You can navigate through the docker container file system by establishing an ssh connection to the container: `docker exec -t -i mycontainer /bin/bash`
 
> This will be in root directory right?

Yes

**Comment by srijansaxena11** [comment]
ok. thanks.
