### ISSUE TITLE
Features Request : Drive File Private

### ISSUE THREAD

**Issue by tldr-cell** [lzzy12/python-aria-mirror-bot#26]
Feature Request add DRIVE_FILE_PRIVATE , i see commit from this [Add option to make uploads private](https://github.com/out386/aria-telegram-mirror-bot/commit/c931492323c9e2e21bd8a79ed3206d9cbb2fb203)

**Comment by lzzy12** [comment]
@tldr-cell If you set IS_TEAM_DRIVE=True (Even for normal folders) the files will be private.

**Comment by tldr-cell** [comment]
@lzzy12 the bad thing is, my administrator disabled upload the new item to my team drive and unable download it. will contact the admin for my issue

**Comment by lzzy12** [comment]
> @lzzy12 the bad thing is, my administrator disabled upload the new item to my team drive and unable download it. will contact the admin for my issue.
> edit; error while upload to my team drive https://del.dog/ubycimimet

What I'm saying is even if you use the edu account (doesn't needs to be a team drive) you can enable that flag and the files won't be public

**Comment by tldr-cell** [comment]
thank you sir, i got it now
