### ISSUE TITLE
Enter API Key: ?

### ISSUE THREAD

**Issue by onoakino** [lzzy12/python-aria-mirror-bot#262]
Chronologically followed the steps. I am already  at the part where I have to execute

"python3 generate_string_session.py"

I am being asked to "Enter API Key:"

What API key is it asking about, and where do I get that API key?

**Comment by shivamdev-lgtm** [comment]
Go to my.teleram.org and sign in. You'll get an option for developers or apps. Get the api key from there. The bot token can be retrieved from @botfather on telegram

**Comment by onoakino** [comment]
Is the API being ask different from the Telegram API that I already put in the TELEGRAM_API config.env? Just to be clear, I am already finished filling in all the relevant fields in the config.env, and that includes the TELEGRAM_API and TELEGRAM_HASH environment fields.

**Comment by shivamdev-lgtm** [comment]
It's the same
