### ISSUE TITLE
Getting "Authorization Error Error 400: invalid_request" when executing "python3 generate_drive_token.py"

### ISSUE THREAD

**Issue by onoakino** [lzzy12/python-aria-mirror-bot#263]
Here is the exact error when I copy-paste the authorization link generated by "python3 generate_drive_token.py "

------------------------
Authorization Error
Error 400: invalid_request

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

You can let the app developer know that this app doesn't comply with one or more Google validation rules.

Request details:
The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google.

If you’re the app developer, make sure that these request details comply with Google policies.

redirect_uri: urn:ietf:wg:oauth:2.0:oob

--------------------------------

I've researched stackoverflow and [this ](https://stackoverflow.com/a/71331562)seemed to be a workaround for the error, however, I am not a programmer, and the suggested solution is way over my head to understand. Would it be possible to make a readme instruction on how to do this step-by-step? I'm stuck.

----
The error might have stemmed from me pasting the authorization link from my Oracle cloud vm (where I am running this project) to my local nework. Also, i used an alternative generate_drive_token.py from [here](https://github.com/Spark-X-Cloud/SparkXcloud-Gdrive-MirrorBot/blob/master/generate_drive_token.py). 

closing.

**Comment by anasty17** [comment]
Just use the script from my repo . Use termux or pc u can't with bot
