### ISSUE TITLE
[Feature Request] Direct link generator‽

### ISSUE THREAD

**Issue by shxnpie** [lzzy12/python-aria-mirror-bot#27]
Maybe add a direct link generator command which generates a direct download link which instantly downloads the file.
EG:-
/direct (file name or even a SR number)

**Comment by AvinashReddy3108** [comment]
You mean Direct download link generator for the files in the Team Drive?

**Comment by lzzy12** [comment]
Can you elaborate what do you mean by that

**Comment by AvinashReddy3108** [comment]
> Can you elaborate what do you mean by that

This might help you understand our request clearly.
https://github.com/AvinashReddy3108/PaperplaneExtended/blob/master/userbot/modules/direct_links.py

**Comment by mriyax** [comment]
@AvinashReddy3108 He means to create a command to generate a direct which doesnt load any page and directly starts the download example : https://www.example.com/filename.zip this will directly start the download and not load any pages ( if the webserver is configured to allow it )

**Comment by lzzy12** [comment]
https://github.com/lzzy12/python-aria-mirror-bot/commit/7ba7bc92acb39ce1395d3e48831d2a048ad533e7
