### ISSUE TITLE
[Issue] Uploading problem

### ISSUE THREAD

**Issue by Bartixxx32** [lzzy12/python-aria-mirror-bot#36]
https://ghostbin.co/paste/378r8

> Im on dev branch

And rest bot or crash, or stuck on 0% of uploading and other upload can stuck like in maybe 40% and dont go more, eta stopped updating, but downloading is fine, only bot stop all uploads, no gdrive limit etc

**Comment by lzzy12** [comment]
>  Im on dev branch

Don't be
