### ISSUE TITLE
Folder upload progress sometimes get totally stuck

### ISSUE THREAD

**Issue by lzzy12** [lzzy12/python-aria-mirror-bot#4]
However the upload works perfectly, the progress of the upload sometimes gets stuck.

**Comment by a092devs** [comment]
I thought i did something wrong! I was about to open an issue!

**Comment by aryanvikash** [comment]
Yeah folder uplaod  stuck.. or something throws error 
```[Errno 2] No such file or directory: '/app/downloads/128/[METADATA]The.Lion.King.2019.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1-FGT'

```

**Comment by lzzy12** [comment]
Seems to be fixed due to 20dae25dc91e554c2ac5953e2c0685669f97d7a1 and 20dae25dc91e554c2ac5953e2c0685669f97d7a1
