### ISSUE TITLE
Stuck after Uploading Complete !

### ISSUE THREAD

**Issue by viperadnan-dummy** [lzzy12/python-aria-mirror-bot#40]
Bot Stucks after Uploading Complete and does not giving link message !

**Comment by a092devs** [comment]
> Bot Stucks after Uploading Complete and does not giving link message !

It would be better if you provide logs and more details to reproduce the issue.

**Comment by viperadnan-dummy** [comment]
[log.txt](https://github.com/lzzy12/python-aria-mirror-bot/files/4202600/log.txt)
![Uploading Screenshot_2020-02-14-09-32-57-644_org.telegram.messenger.jpg…]()
Here is the log file and the error screenshot.  I hope you fix it soon and notify me.

**Comment by lzzy12** [comment]
It happens for all links or any specific link?

**Comment by viperadnan-dummy** [comment]
All links

**Comment by krishne35** [comment]
@viperadnan-dummy Have you cherry-picked the fixed empty files upload to Teamdrive

**Comment by krishne35** [comment]
@viperadnan-dummy I had the same exact issue and it was fixed after that commit

**Comment by viperadnan-dummy** [comment]
Which commit ?

**Comment by a092devs** [comment]
> Which commit ?

This 8b9a73a

**Comment by viperadnan-dummy** [comment]
``2020-02-14T04:52:04.170130+00:00 app[worker.1]: ImportError: cannot import name 'USE_SERVICE_ACCOUNTS'`` this happens

**Comment by a092devs** [comment]
> `2020-02-14T04:52:04.170130+00:00 app[worker.1]: ImportError: cannot import name 'USE_SERVICE_ACCOUNTS'` this happens

You were using master branch? If, yes then this commit wasn't for you. I would recommend to reinstall the bot from scratch. (Use master branch for stability)
