### ISSUE TITLE
Website scraper to download files from multiple sites directly 

### ISSUE THREAD

**Issue by hjyoung1** [lzzy12/python-aria-mirror-bot#46]
Something like [Pyload plugins ](https://github.com/pyload/pyload-plugins)  to download files from various non-ddl sites.
Like many sites which doesn't provide direct links to download this will help in that situation. 
Similar to https://github.com/lzzy12/python-aria-mirror-bot/issues/27

**Comment by lzzy12** [comment]
https://github.com/lzzy12/python-aria-mirror-bot/commit/7ba7bc92acb39ce1395d3e48831d2a048ad533e7
