### ISSUE TITLE
[Issue] Upload never starts.

### ISSUE THREAD

**Issue by familyaria** [lzzy12/python-aria-mirror-bot#48]
Deployed the bot on my Ubuntu system as per the notes.

Now when I send any file to bot it downloads the file but it does not upload anything.

**Comment by viperadnan-dummy** [comment]
@familyaria Check your token.pickle file , make sure you commited it.

**Comment by viperadnan-dummy** [comment]
@familyaria And use latest code.

**Comment by familyaria** [comment]
I have done everything as in readme.

I do have token.pickle file in my folder and then I deployed the bot.

Should we explicitely do something for tocken.pickle file?

**Comment by viperadnan-dummy** [comment]
@familyaria Check requirements.txt and remove httplib2==0.15.0

I also have this issue and solved after this.

You can ask peru in https://t.me/pythonmirrorsupport
