### ISSUE TITLE
It doesn't respond to a bot‘s command

### ISSUE THREAD

**Issue by PengfeiXie** [lzzy12/python-aria-mirror-bot#56]
I try to use a bot to gather the other users' mirror command to resend these command to the mirror-bot in a group. But it just don't react to that command even the chat has been authorized.
Is that not compatible with bots, which means only human users are allowed to send these commands?

**Comment by hjyoung1** [comment]
It's [Telegram limitation](https://core.telegram.org/bots/faq#why-doesnt-my-bot-see-messages-from-other-bots) afaik  
> **Why doesn't my bot see messages from other bots?**
Bots talking to each other could potentially get stuck in unwelcome loops. To avoid this, we decided that bots will not be able to see messages from other bots regardless of mode.
