### ISSUE TITLE
Every user can stop others user download without permission

### ISSUE THREAD

**Issue by Bartixxx32** [lzzy12/python-aria-mirror-bot#57]
Every user can stop others user download without permission

**Comment by Jain2098** [comment]
Found Any Solution?

**Comment by Bartixxx32** [comment]
No soluyion without code edit, you can add propably easislynpermision for authrized users onyl, but users will cant cancel their own torrents

**Comment by lzzy12** [comment]
This will be fixed soon

**Comment by lzzy12** [comment]
Fixed in f4290210b12b644d07a46f8244e1c7d9bfe7ec8d

**Comment by AlbionWhite07** [comment]
@lzzy12 Possible for authorized users to cancel these torrents?
