### ISSUE TITLE
This is not sending the files to Google Drive

### ISSUE THREAD

**Issue by HitaloSama** [lzzy12/python-aria-mirror-bot#58]
I managed to host the bot on Heroku and it manages to download the files, it can also create the folders of each mirror but does not send the file to GDrive, just gets stopped at 0%...

![](https://i.imgur.com/WoJi1ls.jpg)

**Comment by lzzy12** [comment]
Sadly you are on your own on hosting related problems if you are using Heroku. Closing as heroku is not supported.
