### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by emsaumay** [lzzy12/python-aria-mirror-bot#59]
When I ran `python3 generate_drive_token.py`

I got these in return - 

> Traceback (most recent call last):
>   File "generate_drive_token.py", line 17, in <module>
>     'credentials.json', __OAUTH_SCOPE)
>   File "/usr/local/lib/python3.6/dist-packages/google_auth_oauthlib/flow.py", line 197, in from_client_secrets_file
>     client_config = json.load(json_file)
>   File "/usr/lib/python3.6/json/__init__.py", line 299, in load
>     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
>   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)
>

**Comment by lzzy12** [comment]
This is probably due to malformed credentials.json file. Try re downloading it from the console and make sure you select "Others" in type of application. Closing this for now. Join https://t.me/pythonmirrorsupport
