### ISSUE TITLE
大佬或许可以换个上传方式呢

### ISSUE THREAD

**Issue by sorrymyself** [lzzy12/python-aria-mirror-bot#60]
能否加上gclone上传的方式呢？这样就不用担心上传750G的限制了
https://github.com/donwa/gclone

**Comment by hjyoung1** [comment]
使用 [staging-3.0](https://github.com/lzzy12/python-aria-mirror-bot/tree/staging-3.0)  分支，它支持sa帐户，因此您不必担心750G个限制

**Comment by sorrymyself** [comment]
噢，我快要高潮了
2020年4月11日 +0800 23:23 hjyoung1 <notifications@github.com>，写道：

**Comment by sorrymyself** [comment]
大佬，还有一个问题，sa文件夹放哪里呢，以及生成sa的密钥文件，bot怎么引用sa呢
2020年4月11日 +0800 23:23 hjyoung1 <notifications@github.com>，写道：

**Comment by hjyoung1** [comment]
> 大佬，还有一个问题，sa文件夹放哪里呢，以及生成sa的密钥文件，bot怎么引用sa呢 2020年4月11日 +0800 23:23 hjyoung1 <notifications@github.com>，写道：
> […](#)
> 使用 staging-3.0 分支，它支持sa帐户，因此您不必担心750G个限制 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

All instructions to setup bot is in README.md file of staging-3.0 branch.

**Comment by sorrymyself** [comment]
如果能识别群组，而不是手动添加sa到文件夹，那会很good

**Comment by hjyoung1** [comment]
> 如果能识别群组，而不是手动添加sa到文件夹，那会很good

You just need to run one command it will automatically add sa accounts to folder for you. 
https://github.com/lzzy12/python-aria-mirror-bot/blob/staging-3.0/README.md#step-1-generate-service-accounts-what-is-service-account
