### ISSUE TITLE
Is this stagning-3.0 stable enough?

### ISSUE THREAD

**Issue by Bartixxx32** [lzzy12/python-aria-mirror-bot#61]
Hello, i have question, as i know development branch is "development" and unstable, but what about 3.0 branch? Is it also, development? Or its "stable enough"?

**Comment by a092devs** [comment]
As of now staging-3.0 is stable enough for regular usage.

**Comment by Bartixxx32** [comment]
> As of now staging-3.0 is stable enough for regular usage.
Thanks :)
