### ISSUE TITLE
Make UI inorder for download status

### ISSUE THREAD

**Issue by vishansh** [lzzy12/python-aria-mirror-bot#62]
![Screenshot_20200418-124300](https://user-images.githubusercontent.com/63668526/79635854-1a515400-8191-11ea-81c1-89e578e797ce.jpg)
Can you make download status in line it looks best 👌 inline @lzzy12

**Comment by AlbionWhite07** [comment]
@vishansh Edit to your satisfaction here  
python-aria-mirror-bot/bot/helper/ext_utils/bot_utils.py /

**Comment by vishansh** [comment]
Sorry bro I don't know coding can u help

**Comment by vishansh** [comment]
> ![Screenshot_20200418-124300](https://user-images.githubusercontent.com/63668526/79635854-1a515400-8191-11ea-81c1-89e578e797ce.jpg)
> Can you make download status in line it looks best  inline

@lzzy12

**Comment by lzzy12** [comment]
No. You can always fork and make it as per your liking.
