### ISSUE TITLE
Edit torrent trackers

### ISSUE THREAD

**Issue by basimaslamts** [lzzy12/python-aria-mirror-bot#73]
Hey, 
I would love to to know where vould i edit torrent trackers?

**Comment by AlbionWhite07** [comment]
@basimaslamts In aria.sh

**Comment by basimaslamts** [comment]
Could u elaborate on what heads I should add default trackers? Or should I hve to create one

**Comment by basimaslamts** [comment]
Could u elaborate on what heads I should add default trackers? Or should I hve to create one. Thanks 😊 for response

**Comment by hjyoung1** [comment]
Note from python mirror telegram group.

> In aria.sh file add this at beginning:
> 
> export trackers="[udp://tracker.coppersurfer.tk:6969/announce,udp://tracker.leechers-paradise.org:6969/announce,udp://tracker.opentrackr.org:1337/announce,udp://p4p.arenabg.com:1337/announce,udp://9.rarbg.to:2710/announce,udp://9.rarbg.me:2710/announce,udp://tracker.pomf.se:80/announce,udp://tracker.openbittorrent.com:80/announce,udp://exodus.desync.com:6969/announce,udp://tracker.tiny-vps.com:6969/announce,udp://tracker.moeking.me:6969/announce,udp://retracker.lanta-net.ru:2710/announce,udp://open.stealth.si:80/announce,udp://denis.stalker.upeer.me:6969/announce,udp://tracker.torrent.eu.org:451/announce,udp://tracker.cyberia.is:6969/announce,udp://open.demonii.si:1337/announce,udp://ipv4.tracker.harry.lu:80/announce,udp://tracker3.itzmx.com:6961/announce,udp://zephir.monocul.us:6969/announce]"
> 
> Then in the cmd add --bt-tracker=$trackers

**Comment by TorrentW** [comment]
start.sh: line 1: -Ns: command not found
Add this to beginning of start.sh script

tracker_list=curl -Ns https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt | awk '$1' | tr '\n' ',' | cat 
export tracker="[$tracker_list]"

Then just add at the end of aria.sh --bt-tracker=$trackers
used this method

**Comment by krishne35** [comment]
> start.sh: line 1: -Ns: command not found
> Add this to beginning of start.sh script
> 
> tracker_list=curl -Ns https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt | awk '$1' | tr '\n' ',' | cat 
> export tracker="[$tracker_list]"
> 
> Then just add at the end of aria.sh --bt-tracker=$trackers
> used this method

Chek if you have curl installed on docker image

**Comment by TorrentW** [comment]
yes installed

**Comment by krishne35** [comment]
> yes installed

Share your start.sh file
