### ISSUE TITLE
No warnings for unauthorized commands

### ISSUE THREAD

**Issue by Akshaygit1** [lzzy12/python-aria-mirror-bot#78]
Bot doesn't show any warning message when any authorized user use owner only commands.
For example use cancelall or log or restart commands these are only owner filter commands, so when normal user use them bot should show, some kind of warning message.
Like you're not authorized to use this. 
It use to give warns in older master branch.

**Comment by lzzy12** [comment]
Yes That is by design and we don't plan to change this anytime soon

**Comment by srijansaxena11** [comment]
Can you point me where to modify the code so that I can do it on my bot atleast?

**Comment by lzzy12** [comment]
In bot/helper/telegram_helper/filters.py

**Comment by srijansaxena11** [comment]
I could not use sendMessage there as I do not have update object there to be passed in sendMessage. I used REST API for now which is the least efficient method here but works as a workaround. Is there a proper method to do it via the bot methods itself?

**Comment by lzzy12** [comment]
You can call the library functions directly by importing the appropriate methods (see message_utils.py) and import bot object from the bot module..
