### ISSUE TITLE
How to debug and get logs?

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [lzzy12/python-aria-mirror-bot#86]
/log can be used for running nodejs app.
my bot stopped working after few hours.
i am using Google Cloud smallest server with 600 MB RAM.
i can see CPU spikes over last hours.
how can i get log for what happened.

Another Problem: Due to bot stopped in-between the server space that was being used is still used. How to remove those files which were not cleaned.

**Comment by lzzy12** [comment]
> Another Problem: Due to bot stopped in-between the server space that was being used is still used. How to remove those files which were not cleaned.


You can try ```docker  container prune```

**Comment by ParveenBhadooOfficial** [comment]
What about the logs?

**Comment by lzzy12** [comment]
> > Another Problem: Due to bot stopped in-between the server space that was being used is still used. How to remove those files which were not cleaned.
> 
> You can try `docker container prune`

**Comment by lzzy12** [comment]
> What about the logs?
You can ssh into the docker container and get the log.txt

**Comment by hjyoung1** [comment]
You can also use docker logs to see what happened. (if ssh-ing in container not possible)

**Comment by ParveenBhadooOfficial** [comment]
I've used 2 GB RAM and 2 vCPU Server at GCP and still bot stopped.
https://i.imgur.com/NUUkxYn.jpg
Load over 2.0 why?

**Comment by AlbionWhite07** [comment]
@ParveenBhadooOfficial And what does that screenshot prove? Give actual logs

**Comment by ParveenBhadooOfficial** [comment]
> @ParveenBhadooOfficial And what does that screenshot prove? Give actual logs

How to get docker logs. any specific command to get inside docker?

**Comment by AlbionWhite07** [comment]
@ParveenBhadooOfficial https://docs.docker.com/engine/reference/commandline/logs/

**Comment by ParveenBhadooOfficial** [comment]
https://pastebin.com/raw/YbGKTKpG
These are the logs.

Server used is at GCP
Machine type: e2-small (2 vCPUs, 2 GB memory)

**Comment by ParveenBhadooOfficial** [comment]
I used `screen -r` to restore screen session and it started the bot. what could be the problem?

**Comment by lzzy12** [comment]
> I used `screen -r` to restore screen session and it started the bot. what could be the problem?
> 
> Now bot is not responding to /status but /stats is working.

Why are you using screen for running docker image?

**Comment by ParveenBhadooOfficial** [comment]
That could be the problem. as i used NodeJS before and i needed sudo screen to keep it active.
But docker doesn't need that. 

Thank You very much @lzzy12

**Comment by ParveenBhadooOfficial** [comment]
I used direct now without screen.
https://pastebin.com/raw/NhXxJ2Q0

the bot stops responding and then starts again and slow responds. like takes too much time.

**Comment by lzzy12** [comment]
Ye whatever weird stuffs you're doing with the bot by deleting the mirror message or the status message we don't know. Limiting conservation to collaborators
