### ISSUE TITLE
- root - ERROR - The README.md file there to be read! Exiting now!

### ISSUE THREAD

**Issue by robinhoodcharles** [lzzy12/python-aria-mirror-bot#89]
# # #

- [ ] 

- [ ] 
![Screenshot_2020-05-22_05-06-33](https://user-images.githubusercontent.com/54070440/82651377-14b0b900-9bea-11ea-8d70-cebeae3de25b.png)

after following all instructions this is the error in last can you help me out from this

**Comment by 420tushar** [comment]
Atleast share your full image build log 😅. This screenshot shows tells nothing

**Comment by lzzy12** [comment]
Show your config.env (hiding your api keys, etc)

**Comment by smartass08** [comment]
> # #
> * [ ]
> * [ ]
>   ![Screenshot_2020-05-22_05-06-33](https://user-images.githubusercontent.com/54070440/82651377-14b0b900-9bea-11ea-8d70-cebeae3de25b.png)
> 
> after following all instructions this is the error in last can you help me out from this

Did you remove `  
#Remove this line before deploying
_____REMOVE_THIS_LINE_____=True`
from config.env?

**Comment by robinhoodcharles** [comment]
i sovled . ididnt remove the line in config.env
