### ISSUE TITLE
some exception occurred heroku logs

### ISSUE THREAD

**Issue by khagapati** [lzzy12/python-aria-mirror-bot#9]
https://hastebin.com/zajepacoli.pl

**Comment by AVATARX0TIC** [comment]
@khagapati Wtf

**Comment by lzzy12** [comment]
@khagapati we'll need more info than that like How to reproduce the error? And don't paste logs here. Instead post it on https://hastebin.com or https://del.dog or https://paste.ubuntu.com

**Comment by khagapati** [comment]
> @khagapati we'll need more info than that like How to reproduce the error? And don't paste logs here. Instead post it on https://hastebin.com or https://del.dog or https://paste.ubuntu.com

just followed u r README.md deployed to heroku

i think the problem in start.sh

./aria.sh; python -m bot
should be 
.aria.sh; python3 -m bot

**Comment by lzzy12** [comment]
@khagapati No, it isn't. The Docker image only have python3.8. So it automatically calls python3 no matter u use python or python3

**Comment by khagapati** [comment]
> @khagapati No, it isn't. The Docker image only have python3.8. So it automatically calls python3 no matter u use python or python3
ok i will deploy again but
try to deploy to heroku u r self see what happenes

**Comment by lzzy12** [comment]
@khagapati I've deployed it on heroku for more than a week. Don't have any problem like that/error

**Comment by Prakasaka** [comment]
me also getting invalid scope error 1 hour ago i gemerate new token but 20min ago invali scope appear

**Comment by khagapati** [comment]
> me also getting invalid scope error 1 hour ago i generate new token but 20min ago invali scope appear

**Comment by AnggaR96s** [comment]
> > me also getting invalid scope error 1 hour ago i generate new token but 20min ago invali scope appear

Same here

**Comment by Prakasaka** [comment]
> > > me also getting invalid scope error 1 hour ago i generate new token but 20min ago invali scope appear
> 
> Same here

@pythonmirrorsupport join this Official TG Support group

**Comment by lzzy12** [comment]
dd05edb
